spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ColorXJH
    password: 2012WananXJH
    url: jdbc:mysql://49.235.243.26:3306/test
    druid:
      #配置监控页
      stat-view-servlet:
        enabled: true
        login-username: Color
        login-password: 123456
        reset-enable: false
      #监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      #开启拦截器
      filters: stat,wall
      #具体拦截器
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            #所有更新操作都被防火墙拦截，详情参考官方文档
            update-allow: false
      aop-patterns: com.example.springboot2thymeleaf.controller.*
  redis:
    host: 49.235.243.26
    port: 6379
    database: 0
    password: ENC(2qkiPpM4zV7lyslpXXIJpeb/qt13P8b8ho0jRIfg52JvnpNt5K1HKNEAjowUXSy7)
    #新版默认使用的是lettuce,这里指定使用老版本的jedis
    client-type: jedis
    #下面也可以接着配置jedis/lettuce连接池的一些信息
#  sql:
#    init:
#      data-locations: classpath:data-mysql.sql
#      schema-locations: classpath:schema-mysql.sql
#      mode: always

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password


