spring:
  datasource:
    username: root
    password: 2012WananXJH
    url: jdbc:mysql://192.168.40.128:3306/sys #?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  sql:
#    init:
#      mode: always
#      schema-locations:
#        - classpath:department.sql
